# Generated by Django 4.1.2 on 2022-10-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_holder_name', models.CharField(max_length=100)),
                ('acc_no', models.FloatField()),
                ('acc_type', models.CharField(max_length=100)),
            ],
        ),
    ]
